### ISSUE TITLE
npm ERR! Error: Cannot find module './conversions'

### ISSUE THREAD

**Issue by vasylcode** [NibiruChain/ts-sdk#100]
`npm ERR! Error: Cannot find module './conversions'` while installing `npm install @nibiruchain/nibijs`

**Comment by Unique-Divine** [comment]
Hello, what version of node where you using? And what commands did you run, just `npm install`?

**Comment by vasylcode** [comment]
Hey, v18.2.1 for now. Yes, the error occurs after `npm install`, before it I was just creating a project using `npm init` and installing ts libs

**Comment by vasylcode** [comment]
@Unique-Divine any updates?

**Comment by Unique-Divine** [comment]
Everything in this repo is based on the version in the [.nvmrc](https://github.com/NibiruChain/ts-sdk/blob/main/.nvmrc) (node v16). That's what I'm using for local development and the [CI tests](https://github.com/NibiruChain/ts-sdk/blob/main/.github/workflows/tests.yaml). 

Does this problem persist for you with v16.* ?

**Comment by vasylcode** [comment]
I did not test v16.*
Why you are not using the LTS version of node ?

**Comment by cgilbe27** [comment]
I installed the package in a test folder using node v18.2.0 and the latest @nibiruchain/nibijs@0.19.9. 

I could not duplicate the issue.

We also do not have any folder called "./conversions", this sounds like a local issue.

@vasylcode please re-open this ticket if this issue persists and you have a "[Minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example)"
