### ISSUE TITLE
bug: update the token list based on existing pool.

### ISSUE THREAD

**Issue by matthiasmatt** [NibiruChain/ts-sdk#117]
![image](https://user-images.githubusercontent.com/97468149/229108990-c24506d0-813f-4f45-9060-bb305d5812c1.png)
On this image, i can select to swap from nibi to usdt, but there's no nibi/usdt pool.

which means that if i select usdt, and then press swap i get a tx failed popup with no indication.

We should update the list of token you can swap to when selecting the token from.

**Comment by Unique-Divine** [comment]
Yes, the list for the dropdown needs to be filtered based on which pools exist. 

### Example implementation

1. The list of available tokens on the "to" asset can be exhaustive, but it should be split into `paired (Set)` and `notPaired (Set)`.  
2. The `paired` tokens should be listed first and have the default background.
3. Tokens in the `notPaired` set should be listed after and be darkened out. This darkening will make it more intuitive that the pool corresponding to the asset selection doesn't exist.
4. Whenever the menu is clicked, that asset should be selected in its designated spot, however the other asset should be forced to be one of the available assets.

For example, if I have `{ from: "NIBI", to: "NUSD" }` like in the description image, then the resulting state change should look as follows:
- [x] Selecting NIBI as "to" → `{ from: "NUSD", to: "NIBI" }`
- [x] Selecting NUSD as "to" → (simply closes the menu)
- [x] Selecting USDT as "to" → `{ from: "xxxx", to: "USDT" }`, where `xxxx` is an asset paired against USDT.

**Comment by cgilbe27** [comment]
This task is in reference to the web app and not the ts-sdk
