### ISSUE TITLE
TS-SDK polishing

### ISSUE THREAD

**Issue by cgilbe27** [NibiruChain/ts-sdk#272]
https://nibiru.fi/docs/dev/x/Nibiru-Chain/bank.html

Plus another

**Comment by cgilbe27** [comment]
inflation

From cosmjs or build flag in proto generation

**Comment by cgilbe27** [comment]
Docs based on js doc, arch diagram, explainations for heart monitor and txclient
Update readme
Clean up code

**Comment by cgilbe27** [comment]
Improve test coverage

**Comment by cgilbe27** [comment]
Ability to configure docs with docs website

**Comment by cgilbe27** [comment]
Already using typedoc

**Comment by cgilbe27** [comment]
Left:
- [x] Tests
- [x] More folder reorg
- [ ] Typedocs
- [ ] Readme
- [x] Bank/inflation protos as SDK MsgFactory
- [x] Pathing issue
- [ ] Re-enable sonarqube quality gate

**Comment by cgilbe27** [comment]
Re-enable sonarqube quality gate

**Comment by Unique-Divine** [comment]
Seems closed / forgotten issue
