### ISSUE TITLE
feat: gql - use explicitly defined fields for queries instead of default objects

### ISSUE THREAD

**Issue by ruslan-sh-r** [NibiruChain/ts-sdk#348]
In case no fields specified for the query return nothing instead of using default field list.

Example with default fields list:
https://github.com/NibiruChain/ts-sdk/blob/dabe094fcaafaf5c23668616e10905c960832347/src/gql/query/oracle.ts#L59-L68

**Comment by cgilbe27** [comment]
Closed as resolved
