### ISSUE TITLE
Cannot read properties of undefined (reading 'tokenfactory')

### ISSUE THREAD

**Issue by baunvb** [NibiruChain/ts-sdk#359]
I would like to mint token to an address but get this error "Cannot read properties of undefined (reading 'tokenfactory')"

This is my code:

`
async function main() {
  const signer = await newSignerFromMnemonic(process.env.MNEMONIC)
  const txClient = await NibiruTxClient.connectWithSigner(chain.endptTm, signer)

  const [{ address: fromAddr }] = await signer.getAccounts()
 
  const msgMint = Msg.tokenfactory.mint({
    sender: fromAddr,
    coin: {
      denom: "tf/nibi1qqz4d2fdg4padtqg9p8xq8jqj8zxuansd9g4xy/CAFE",
      amount: '1'
    }, 
    mintTo: "nibi15lnskcs8deatupc5uj9txc9p99lefuazazpggc"
  })

  const txResp = await txClient.signAndBroadcast(fromAddr, [msgMint], "auto")
  console.log(txResp)
}
`

**Comment by cgilbe27** [comment]
In the future you will be able to do:

```
import { newSignerFromMnemonic, NibiruTxClient } from "./sdk"

export const b = async () => {
  const signer = await newSignerFromMnemonic(
    ""
  )
  const txClient = await NibiruTxClient.connectWithSigner(
    "https://rpc.nibiru.fi",
    signer
  )

  const [{ address: fromAddr }] = await signer.getAccounts()
  const msgMint = await txClient.nibiruExtensions.tokenFactoryMsg.mint({
    sender: fromAddr,
    coin: {
      denom: "tf/nibi1qqz4d2fdg4padtqg9p8xq8jqj8zxuansd9g4xy/CAFE",
      amount: "1",
    },
    mintTo: "nibi15lnskcs8deatupc5uj9txc9p99lefuazazpggc",
  })

  console.log(msgMint)
}

```

**Comment by baunvb** [comment]
I set rpc to testnet-1 but it does not work.
const txClient = await NibiruTxClient.connectWithSigner("https://rpc.testnet-1.nibiru.fi", signer)
It show error: Error: Query failed with (6): unknown query path: unknown request
