### ISSUE TITLE
feat: exception handling - parse tx response payloads with more descriptive type hints

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#60]
### Exception Handling

Common examples:
- [ ] "incorrect account sequence" | Account sequence mismatch errors | Example here: https://github.com/cosmos/cosmos-sdk/issues/11597
- [ ] "insufficient funds"
- [ ] "out of gas"
- [ ] "insufficient fees"

- Ref: https://github.com/cosmos/cosmos-sdk/blob/main/types/errors/errors.go

**Comment by CalicoNino** [comment]
Completed with https://github.com/NibiruChain/web-app/pull/1095
